(function(){
  function atualizarEntendaTermos(secao){const exp=secao.querySelector('#exp-sst');if(!exp)return;exp.className='hidden bg-slate-100 border border-slate-300 p-3 rounded mb-4 text-xs text-slate-700 space-y-3';exp.innerHTML='<div><strong>PGR — Programa de Gerenciamento de Riscos:</strong> documento central do GRO, composto pelo inventário de riscos e pelo plano de ação.</div><div><strong>PCMSO — Programa de Controle Médico de Saúde Ocupacional:</strong> programa médico da NR-7 elaborado a partir dos riscos identificados.</div><div><strong>LTCAT — Laudo Técnico das Condições Ambientais do Trabalho:</strong> laudo previdenciário que registra exposição a agentes nocivos e subsidia informações como o PPP.</div>';}
  function removerCipaOriginal(secao){const h=[...secao.querySelectorAll('h4')].find(x=>(x.textContent||'').includes('CIPA'));const card=h&&h.closest('.bg-white');if(card)card.remove();}
  function criar(){
    const secao=document.getElementById('sst');if(!secao)return false;atualizarEntendaTermos(secao);removerCipaOriginal(secao);const conteudo=secao.querySelector('.space-y-4.text-sm.text-gray-700');if(!conteudo)return false;document.getElementById('cma-sst-atualizacoes')?.remove();
    const w=document.createElement('div');w.id='cma-sst-atualizacoes';w.className='space-y-4';w.innerHTML=`
      <div id="cma-sst-programas" class="bg-white p-4 rounded border border-gray-200 shadow-sm"><h4 class="font-bold text-blue-950 text-sm mb-3">Programas e Laudos de SST</h4><div class="space-y-4 text-gray-600 text-sm leading-relaxed"><div><p><strong class="text-blue-950">PGR — Programa de Gerenciamento de Riscos</strong></p><p>Identifica, avalia e controla os riscos ocupacionais por meio do inventário de riscos e do plano de ação. A avaliação de riscos deve ser revista, no máximo, a cada <strong>2 anos</strong>, ou em até <strong>3 anos</strong> para organizações com certificação válida em sistema de gestão de SST, sem prejuízo de revisão antecipada quando ocorrerem mudanças relevantes, acidentes, doenças, falhas de prevenção ou alteração legal.</p></div><div class="border-t border-gray-100 pt-3"><p><strong class="text-blue-950">PCMSO — Programa de Controle Médico de Saúde Ocupacional</strong></p><p>Organiza o acompanhamento clínico e os exames ocupacionais a partir dos riscos identificados no PGR.</p><ul class="list-disc list-inside space-y-1 mt-1"><li><strong>Admissional:</strong> antes do início das atividades;</li><li><strong>Periódico:</strong> conforme a periodicidade prevista na NR-7 e os riscos ocupacionais;</li><li><strong>Retorno ao trabalho:</strong> antes da reassunção, nas hipóteses previstas na NR-7;</li><li><strong>Mudança de risco:</strong> antes da mudança;</li><li><strong>Demissional:</strong> conforme o prazo e as hipóteses de dispensa previstas na NR-7;</li><li><strong>Relatório analítico:</strong> elaborado anualmente.</li></ul></div><div class="border-t border-gray-100 pt-3"><p><strong class="text-blue-950">LTCAT — Laudo Técnico das Condições Ambientais do Trabalho</strong></p><p>Registra tecnicamente a exposição a agentes nocivos para fins previdenciários. Não há validade única aplicável a todas as empresas: deve permanecer atualizado quando houver mudança relevante nas condições ambientais, processo, máquinas, equipamentos, proteção ou organização do trabalho.</p></div></div></div>
      <div id="cma-sst-riscos-psicossociais" class="bg-white p-4 rounded border border-gray-200 shadow-sm"><h4 class="font-bold text-blue-950 text-sm mb-2">Riscos Psicossociais — NR-1 e PGR</h4><p class="text-gray-600 leading-relaxed text-sm mb-3">Desde 26 de maio de 2026, a NR-1 inclui expressamente os fatores de risco psicossociais relacionados ao trabalho no GRO. A empresa deve avaliá-los dentro do PGR, considerando as condições e a organização do trabalho.</p><ul class="list-disc list-inside space-y-1 text-gray-600 text-sm"><li>sobrecarga, excesso de demandas e pressão;</li><li>falta de suporte da liderança e organização inadequada do trabalho;</li><li>conflitos, assédio e outras formas de violência;</li><li>baixa autonomia, falhas de comunicação e insegurança relacionada ao trabalho.</li></ul></div>
      <div class="bg-amber-50 border-l-4 border-amber-600 p-4 rounded-r shadow-sm"><strong class="text-amber-900 block mb-1">Orientação CMA — atualização do PGR</strong><p class="text-amber-950 leading-relaxed text-sm">A empresa deve alinhar com a clínica ou profissional responsável pelo SST a metodologia de avaliação dos riscos psicossociais e o respectivo plano de ação, conforme a realidade da organização.</p></div>
      <div id="cma-sst-cipa" class="bg-white p-4 rounded border border-gray-200 shadow-sm"><h4 class="font-bold text-blue-950 text-sm mb-2">CIPA — Comissão Interna de Prevenção de Acidentes e de Assédio</h4><p class="text-sm text-gray-600 leading-relaxed mb-2">A constituição e o dimensionamento dependem das regras da NR-5. Quando não houver enquadramento para comissão, deve ser observada a regra aplicável ao representante nomeado.</p><ul class="list-disc list-inside space-y-1 text-gray-600 text-sm mb-3"><li>prevenção de acidentes e doenças relacionadas ao trabalho;</li><li>acompanhamento das medidas de prevenção;</li><li>ações de prevenção e combate ao assédio sexual e demais formas de violência;</li><li>integração com o PGR e as demais ações de SST.</li></ul><div class="bg-red-50 border-l-4 border-red-600 p-3 rounded-r"><p class="text-xs text-red-900 font-semibold leading-relaxed"><strong>Orientação CMA:</strong> confirme com a clínica ou responsável técnico o dimensionamento, treinamentos e procedimentos aplicáveis ao estabelecimento.</p></div></div>
      <div id="cma-sst-campanhas" class="bg-white p-4 rounded border border-gray-200 shadow-sm"><h4 class="font-bold text-blue-950 text-sm mb-2">Campanhas de Vacinação e Prevenção em Saúde</h4><p class="text-gray-600 leading-relaxed text-sm mb-3">A Lei nº 15.377/2026 estabeleceu deveres de informação e conscientização sobre campanhas oficiais de vacinação, HPV e prevenção dos cânceres previstos na legislação.</p><ul class="list-disc list-inside space-y-1 text-gray-600 text-sm mb-3"><li>divulgar campanhas oficiais de vacinação;</li><li>promover conscientização sobre HPV e prevenção;</li><li>orientar sobre acesso a serviços de diagnóstico e prevenção;</li><li>informar sobre as ausências legalmente justificadas para exames preventivos.</li></ul><div class="bg-blue-50 border-l-4 border-blue-900 p-3 rounded-r"><p class="text-blue-950 text-sm leading-relaxed"><strong>Exames preventivos:</strong> observar as hipóteses e limites previstos no art. 473 da CLT e legislação correlata.</p></div></div>
      <div class="bg-red-50 border-l-4 border-red-600 p-4 rounded-r shadow-sm"><strong class="text-red-800 block mb-1">Atenção à documentação</strong><p class="text-red-950 leading-relaxed text-sm">Os documentos e ações de SST devem permanecer coerentes com a realidade da empresa. Mudanças em ambiente, processos, funções, máquinas, riscos ou organização do trabalho devem ser comunicadas ao responsável técnico.</p></div>`;
    conteudo.appendChild(w);return true;
  }
  let n=0;(function tentar(){if(criar())return;if(++n<40)setTimeout(tentar,200)})();
})();
