(function(){
  let deepLinkInstalado=false,showSectionOriginal=null;

  function botaoClasse(){return 'w-full text-left px-3 py-2 rounded text-sm font-medium text-gray-600 hover:bg-gray-50 hover:translate-x-0.5 transition-all flex items-center border-l-4 border-transparent';}
  function card(sigla,titulo,texto){return `<article class="cma-modelo-card" data-categoria="${sigla}"><div class="cma-modelo-card-top"><div class="cma-modelo-card-icon">${sigla.slice(0,2).toUpperCase()}</div><h3>${titulo}</h3></div><p>${texto}</p><div class="cma-modelo-card-footer"><span class="cma-modelo-count">Nenhum arquivo cadastrado</span><span class="cma-modelo-status">Em preparação</span></div></article>`;}

  function instalarEstilo(){
    if(document.getElementById('cma-modelos-style'))return;
    const st=document.createElement('style');st.id='cma-modelos-style';st.textContent=`
      .cma-modelos-head{padding-bottom:18px;margin-bottom:20px;border-bottom:1px solid #e5e7eb}.cma-modelos-title-row{display:flex;align-items:center;gap:14px}.cma-modelos-title-icon{width:44px;height:44px;border-radius:12px;display:grid;place-items:center;background:#eff6ff;color:#172554;flex:0 0 auto}.cma-modelos-title-icon svg{width:23px;height:23px;fill:none;stroke:currentColor;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}.cma-modelos-head h2{margin:0;color:#172554;font-size:24px;font-weight:800;line-height:1.2}.cma-modelos-head p{margin:4px 0 0;color:#64748b;font-size:13px}.cma-modelos-info{display:flex;flex-direction:column;gap:4px;margin-bottom:20px;padding:15px 17px;border-left:4px solid #172554;border-radius:0 10px 10px 0;background:#eff6ff;color:#1e3a8a;font-size:13px;line-height:1.5}.cma-modelos-info strong{font-size:13px;color:#172554}.cma-modelos-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.cma-modelo-card{display:flex;flex-direction:column;min-height:150px;padding:17px;border:1px solid #e2e8f0;border-radius:13px;background:#fff;box-shadow:0 5px 16px rgba(15,23,42,.04);transition:.2s}.cma-modelo-card:hover{transform:translateY(-2px);border-color:#cbd5e1;box-shadow:0 10px 24px rgba(15,23,42,.08)}.cma-modelo-card-top{display:flex;align-items:center;gap:11px;margin-bottom:10px}.cma-modelo-card-icon{width:37px;height:37px;border-radius:10px;display:grid;place-items:center;background:#f8fafc;border:1px solid #e2e8f0;color:#1e3a8a;font-weight:800;font-size:13px}.cma-modelo-card h3{margin:0;color:#172554;font-size:15px;font-weight:800}.cma-modelo-card p{margin:0 0 14px;color:#64748b;font-size:12.5px;line-height:1.5;flex:1}.cma-modelo-card-footer{display:flex;align-items:center;justify-content:space-between;padding-top:11px;border-top:1px solid #f1f5f9}.cma-modelo-count{font-size:11px;font-weight:700;color:#94a3b8}.cma-modelo-status{padding:5px 8px;border-radius:999px;background:#f1f5f9;color:#64748b;font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.03em}.cma-modelos-empty{display:flex;align-items:center;gap:13px;margin-top:18px;padding:15px;border:1px dashed #cbd5e1;border-radius:12px;background:#f8fafc}.cma-modelos-empty-icon{width:34px;height:34px;display:grid;place-items:center;border-radius:50%;background:#fff;border:1px solid #dbe3ee;color:#1e3a8a;font-size:22px}.cma-modelos-empty strong{display:block;color:#334155;font-size:12px}.cma-modelos-empty p{margin:2px 0 0;color:#94a3b8;font-size:11px;line-height:1.4}@media(max-width:700px){.cma-modelos-grid{grid-template-columns:1fr}.cma-modelos-head h2{font-size:21px}.cma-modelos-title-row{align-items:flex-start}}
    `;document.head.appendChild(st);
  }

  function criarArea(){
    const menu=document.getElementById('manual-menu'),main=document.querySelector('#manual-conteudo main');if(!menu||!main)return false;
    if(!document.getElementById('modelos')){
      const botao=document.createElement('button');botao.type='button';botao.setAttribute('onclick',"showSection('modelos', this)");botao.className=botaoClasse();botao.innerHTML='<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide w-4 h-4 mr-2.5 shrink-0"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6"/><path d="M9 13h6"/><path d="M9 17h6"/></svg> Modelos de Documentos';
      const baseBtn=typeof getMenuButton==='function'?getMenuButton('baselegal'):null;if(baseBtn)menu.insertBefore(botao,baseBtn);else menu.appendChild(botao);
      const s=document.createElement('section');s.id='modelos';s.className='manual-section hidden fade-in';s.innerHTML=`<div class="cma-modelos-head"><div class="cma-modelos-title-row"><div class="cma-modelos-title-icon"><svg viewBox="0 0 24 24"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6"/><path d="M9 13h6"/><path d="M9 17h6"/></svg></div><div><h2>Modelos de Documentos</h2><p>Central de documentos para apoio às rotinas do Departamento Pessoal.</p></div></div></div><div class="cma-modelos-info"><strong>Biblioteca de modelos CMA</strong><span>Esta área está preparada para receber os modelos oficiais. Arquivos somente serão marcados como disponíveis após validação da versão definitiva.</span></div><div class="cma-modelos-grid">${card('admissao','Admissão','Contratos, fichas, declarações e documentos utilizados no início do vínculo.')}${card('jornada','Jornada e Ponto','Banco de horas, alteração de horário, compensação e controles de jornada.')}${card('ferias','Férias','Avisos, recibos, comunicados e documentos relacionados às férias.')}${card('disciplinar','Advertências e Suspensões','Modelos para aplicação de medidas disciplinares e registro de ocorrências.')}${card('rescisao','Rescisão','Comunicados, pedidos de demissão, avisos e documentos de encerramento do vínculo.')}${card('outros','Outros Documentos','Declarações, termos e modelos complementares de Departamento Pessoal.')}</div><div class="cma-modelos-empty"><div class="cma-modelos-empty-icon">+</div><div><strong>Estrutura pronta para novos arquivos</strong><p>Os modelos definitivos poderão ser adicionados por categoria sem alterar a estrutura do Manual.</p></div></div>`;
      const base=document.getElementById('baselegal');if(base)main.insertBefore(s,base);else main.appendChild(s);
      if(typeof manualSections!=='undefined'&&!manualSections.some(x=>x.id==='modelos')){const pos=manualSections.findIndex(x=>x.id==='baselegal');manualSections.splice(pos>=0?pos:manualSections.length,0,{id:'modelos',nome:'Modelos de Documentos'});}
    }
    instalarEstilo();instalarLinksDiretos();carregarBootstrap();return true;
  }

  function carregarBootstrap(){if(document.querySelector('script[data-cma-bootstrap]'))return;const s=document.createElement('script');s.dataset.cmaBootstrap='1';s.src='core/bootstrap.js?v=20260823';s.async=false;document.body.appendChild(s);}
  function idHash(){const id=decodeURIComponent((location.hash||'').replace(/^#/,''));return typeof manualSections!=='undefined'&&manualSections.some(x=>x.id===id)?id:null;}
  function instalarLinksDiretos(){
    if(deepLinkInstalado||typeof window.showSection!=='function')return;deepLinkInstalado=true;showSectionOriginal=window.showSection;
    window.showSection=function(id,btn){showSectionOriginal(id,btn);const h='#'+encodeURIComponent(id);if(location.hash!==h)history.pushState({section:id},'',h);};
    const inicial=idHash();if(inicial)setTimeout(()=>showSectionOriginal(inicial,typeof getMenuButton==='function'?getMenuButton(inicial):null),0);
    addEventListener('popstate',()=>{const id=idHash()||'apresentacao';showSectionOriginal(id,typeof getMenuButton==='function'?getMenuButton(id):null);});
    addEventListener('hashchange',()=>{const id=idHash();if(id)showSectionOriginal(id,typeof getMenuButton==='function'?getMenuButton(id):null);});
  }

  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',criarArea);else criarArea();
})();
