(function(){
  let organizando=false,agendado=false,ultimoAtivo='';
  const registro=()=>window.CMARegistroManual;
  const grupos=()=>registro()?.gruposMenu||[];
  const itensDoGrupo=id=>registro()?.paginasDoGrupo(id).map(p=>p.id)||[];

  function carregarPaginasSST(){if(document.getElementById('cma-sst-paginas-loader'))return;const s=document.createElement('script');s.id='cma-sst-paginas-loader';s.src='sst/sst-paginas.js?v='+(window.CMA_MANUAL_VERSION||'20260824');document.body.appendChild(s);}
  function instalarEstilo(){if(document.getElementById('cma-ferramentas-menu-style'))return;const st=document.createElement('style');st.id='cma-ferramentas-menu-style';st.textContent=`@media(min-width:1024px){#manual-menu{max-height:calc(100vh - 3rem);overflow-y:auto;overscroll-behavior:contain;scrollbar-gutter:stable;padding-right:10px}#manual-menu::-webkit-scrollbar{width:7px}#manual-menu::-webkit-scrollbar-track{background:transparent}#manual-menu::-webkit-scrollbar-thumb{background:#cbd5e1;border-radius:999px}#manual-menu::-webkit-scrollbar-thumb:hover{background:#94a3b8}}.cma-sumario-grupo{margin:3px 0}.cma-sumario-toggle{display:flex;align-items:center;width:100%;gap:9px;padding:9px 12px;border:0;border-left:4px solid transparent;border-radius:6px;background:transparent;color:#475569;font-size:14px;font-weight:700;text-align:left;cursor:pointer;transition:.18s}.cma-sumario-toggle:hover{background:#f8fafc;color:#172554}.cma-sumario-toggle svg{width:16px;height:16px;flex:0 0 16px}.cma-sumario-seta{margin-left:auto;font-size:15px;line-height:1;transition:transform .2s;color:#94a3b8}.cma-sumario-grupo.is-open>.cma-sumario-toggle{background:#f8fafc;color:#172554}.cma-sumario-grupo.is-open>.cma-sumario-toggle .cma-sumario-seta{transform:rotate(180deg)}.cma-sumario-submenu{display:none;margin:2px 0 5px 10px;padding-left:10px;border-left:1px solid #e2e8f0}.cma-sumario-grupo.is-open>.cma-sumario-submenu{display:block}.cma-sumario-submenu>button{padding-left:10px!important;font-size:13px!important}.cma-sumario-submenu>button svg{width:15px!important;height:15px!important}.cma-sumario-grupo.is-direct>.cma-sumario-submenu{display:none!important}.cma-sumario-grupo.is-direct.is-current>.cma-sumario-toggle{background:#eff6ff;color:#082f7d;border-left-color:#2563eb}.cma-menu-ferramenta-oculta{display:none!important}#manual-menu>.border-t{display:none!important}@media(max-width:640px){.cma-sumario-toggle{font-size:15px;padding-top:10px;padding-bottom:10px}.cma-sumario-submenu>button{font-size:14px!important}}`;document.head.appendChild(st);}
  function localizarBotao(id){const menu=document.getElementById('manual-menu');if(!menu)return null;return [...menu.querySelectorAll('button')].find(b=>!b.classList.contains('cma-sumario-toggle')&&(b.getAttribute('onclick')||'').includes(`'${id}'`))||null;}
  function removerFiscalizacao(){localizarBotao('fiscalizacao')?.remove();if(typeof manualSections!=='undefined'){const i=manualSections.findIndex(x=>x.id==='fiscalizacao');if(i>=0)manualSections.splice(i,1);}}
  function fecharOutros(exceto){document.querySelectorAll('#manual-menu .cma-sumario-grupo.is-open').forEach(g=>{if(g!==exceto){g.classList.remove('is-open');g.querySelector(':scope > .cma-sumario-toggle')?.setAttribute('aria-expanded','false');}});}
  function abrirGrupo(grupo,estado){if(!grupo||grupo.classList.contains('is-direct'))return;if(estado)fecharOutros(grupo);grupo.classList.toggle('is-open',estado);grupo.querySelector(':scope > .cma-sumario-toggle')?.setAttribute('aria-expanded',String(estado));}
  function grupoDoItem(id){const p=registro()?.pagina(id);return p?.grupo?document.getElementById(`cma-sumario-${p.grupo}`):null;}
  function itemAtivo(){for(const p of registro()?.paginas||[]){const sec=document.getElementById(p.id);if(sec?.classList.contains('active'))return p.id;const b=localizarBotao(p.id);if(b&&(b.classList.contains('bg-blue-50')||b.classList.contains('active-menu-btn')))return p.id;}return '';}
  function abrirPaginaGrupo(cfg){if(!cfg.pagina)return false;if(typeof showSection==='function')showSection(cfg.pagina,localizarBotao(cfg.pagina));return true;}
  function criarEstruturaGrupo(menu,cfg){let grupo=document.getElementById(`cma-sumario-${cfg.id}`);if(grupo)return grupo;grupo=document.createElement('div');grupo.id=`cma-sumario-${cfg.id}`;grupo.className='cma-sumario-grupo'+(cfg.direto?' is-direct':'');const seta=cfg.direto?'':'<span class="cma-sumario-seta" aria-hidden="true">⌄</span>';grupo.innerHTML=`<button type="button" class="cma-sumario-toggle" aria-expanded="false"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${cfg.icone}</svg><span>${cfg.titulo}</span>${seta}</button><div id="cma-sumario-submenu-${cfg.id}" class="cma-sumario-submenu"></div>`;menu.appendChild(grupo);grupo.querySelector('.cma-sumario-toggle').addEventListener('click',e=>{e.stopPropagation();if(!abrirPaginaGrupo(cfg))abrirGrupo(grupo,!grupo.classList.contains('is-open'));});return grupo;}
  function atualizarDiretos(alvo){grupos().filter(g=>g.direto).forEach(cfg=>{const ids=itensDoGrupo(cfg.id);document.getElementById(`cma-sumario-${cfg.id}`)?.classList.toggle('is-current',ids.includes(alvo));});}
  function reorganizar(){const menu=document.getElementById('manual-menu');if(!menu||!registro()||organizando)return false;organizando=true;try{removerFiscalizacao();const intro=localizarBotao('introducao');let ancora=intro?intro.nextSibling:null;grupos().forEach(cfg=>{const grupo=criarEstruturaGrupo(menu,cfg);if(ancora!==grupo){if(ancora)menu.insertBefore(grupo,ancora);else menu.appendChild(grupo);}const submenu=grupo.querySelector('.cma-sumario-submenu');itensDoGrupo(cfg.id).forEach(id=>{const botao=localizarBotao(id);if(!botao)return;if(botao.parentElement!==submenu)submenu.appendChild(botao);botao.classList.toggle('cma-menu-ferramenta-oculta',!!cfg.direto);if(!botao.dataset.cmaGrupoLigado){botao.dataset.cmaGrupoLigado='1';botao.addEventListener('click',()=>abrirGrupo(grupo,true));}});ancora=grupo.nextSibling;});const ativo=itemAtivo(),hash=(location.hash||'').replace(/^#/,''),alvo=ativo||hash;atualizarDiretos(alvo);if(alvo&&alvo!==ultimoAtivo){ultimoAtivo=alvo;const g=grupoDoItem(alvo);if(g&&!g.classList.contains('is-direct'))abrirGrupo(g,true);}return true;}finally{organizando=false;}}
  function agendar(){if(agendado)return;agendado=true;requestAnimationFrame(()=>{agendado=false;reorganizar();});}
  function observar(){const menu=document.getElementById('manual-menu'),conteudo=document.getElementById('manual-conteudo');if(!menu)return;const obs=new MutationObserver(()=>{if(!organizando)agendar();});obs.observe(menu,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});if(conteudo)obs.observe(conteudo,{subtree:true,attributes:true,attributeFilter:['class']});}
  function iniciar(){carregarPaginasSST();instalarEstilo();let tentativas=0;(function tentar(){if(!registro()){if(++tentativas<60)setTimeout(tentar,150);return;}const menu=document.getElementById('manual-menu');if(menu){reorganizar();observar();setTimeout(reorganizar,600);setTimeout(reorganizar,1800);return;}if(++tentativas<60)setTimeout(tentar,200);})();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',iniciar);else iniciar();
})();
