(function(){
  if(window.CMAFerramentas)return;
  function texto(id){const el=document.getElementById(id);return el?(el.value||'').trim():'';}
  function numero(id){const el=document.getElementById(id);if(!el)return 0;const n=parseFloat(String(el.value||'0').replace(',','.'));return Number.isFinite(n)?n:0;}
  function moeda(v){return (Number(v)||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});}
  function limpar(secao,callback){if(!secao)return;secao.querySelectorAll('input[type="text"],input[type="number"],textarea').forEach(el=>el.value=el.type==='number'?(el.dataset.cmaDefault||'0'):'');const grupos=new Set([...secao.querySelectorAll('input[type="radio"]')].map(x=>x.name));grupos.forEach(nome=>{const radios=[...secao.querySelectorAll(`input[type="radio"][name="${CSS.escape(nome)}"]`)];const padrao=radios.find(r=>r.dataset.cmaDefault==='true')||radios[0];radios.forEach(r=>r.checked=r===padrao);});secao.querySelectorAll('select').forEach(el=>el.selectedIndex=0);secao.querySelectorAll('input').forEach(el=>{el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));});if(typeof callback==='function')callback();}
  function garantirIdentificacao(secao){if(!secao||document.getElementById('cma-custo-empresa'))return;const form=secao.querySelector('.cma-custo-form');if(!form)return;const primeiraLabel=form.querySelector('.cma-custo-label');if(!primeiraLabel)return;const bloco=document.createElement('div');bloco.className='cma-ferramenta-identificacao';bloco.innerHTML='<div><label class="cma-custo-label" for="cma-custo-empresa">Empresa</label><input id="cma-custo-empresa" class="cma-ferramenta-texto" type="text" autocomplete="organization" placeholder="Nome da empresa"></div><div><label class="cma-custo-label" for="cma-custo-empregado">Nome do empregado</label><input id="cma-custo-empregado" class="cma-ferramenta-texto" type="text" autocomplete="name" placeholder="Nome do empregado"></div>';form.insertBefore(bloco,primeiraLabel);}
  function adicionarAcoes(secaoId,{onLimpar}={}){const secao=document.getElementById(secaoId);if(!secao||secao.querySelector('.cma-ferramenta-acoes'))return;const cab=secao.querySelector(':scope > div:first-child');if(!cab)return;const acoes=document.createElement('div');acoes.className='cma-ferramenta-acoes';const btn=document.createElement('button');btn.type='button';btn.className='cma-ferramenta-limpar';btn.textContent='Limpar campos';btn.addEventListener('click',()=>limpar(secao,onLimpar));acoes.appendChild(btn);cab.appendChild(acoes);}
  function identificacao(){return {empresa:texto('cma-custo-empresa'),empregado:texto('cma-custo-empregado')};}
  window.CMAFerramentas={texto,numero,moeda,limpar,garantirIdentificacao,adicionarAcoes,identificacao,versao:'1.1'};
  if(!document.getElementById('cma-ferramentas-base-style')){const st=document.createElement('style');st.id='cma-ferramentas-base-style';st.textContent='.cma-ferramenta-identificacao{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:4px}.cma-ferramenta-texto{width:100%;padding:11px 12px;border:1px solid #cbd5e1;border-radius:9px;background:#fff;color:#0f172a;font-size:14px;outline:none}.cma-ferramenta-texto:focus{border-color:#2563eb;box-shadow:0 0 0 3px rgba(37,99,235,.1)}.cma-ferramenta-acoes{display:flex;align-items:center;gap:8px;margin-left:auto}.cma-ferramenta-limpar{padding:7px 10px;border:1px solid #cbd5e1;border-radius:8px;background:#fff;color:#475569;font-size:12px;font-weight:800;cursor:pointer}.cma-ferramenta-limpar:hover{background:#f8fafc;color:#172554}@media(max-width:640px){.cma-ferramenta-identificacao{grid-template-columns:1fr}.cma-ferramenta-texto{font-size:16px}.cma-ferramenta-acoes{width:100%;margin:10px 0 0}.cma-ferramenta-limpar{width:100%;font-size:14px;padding:10px}}';document.head.appendChild(st);}
  function aplicar(){const custo=document.getElementById('custo-empregado');if(custo){garantirIdentificacao(custo);adicionarAcoes('custo-empregado');}}
  aplicar();document.addEventListener('cma:modulos-prontos',aplicar);
})();
