(function(){
  function incluir(){
    const secao=document.getElementById('baselegal');if(!secao||document.getElementById('cma-bases-legais-20260823'))return;
    const bloco=document.createElement('div');bloco.id='cma-bases-legais-20260823';bloco.className='mt-6 space-y-4 text-sm text-gray-700';
    bloco.innerHTML=`
      <div class="bg-blue-50 border-l-4 border-blue-900 p-4 rounded-r shadow-sm"><strong class="text-blue-950 block mb-1">Bases legais incluídas nas atualizações do Manual</strong><p class="text-blue-950 leading-relaxed">Referências utilizadas nas páginas adicionadas e revisadas. O conteúdo deve ser revalidado sempre que houver alteração normativa.</p></div>
      <div class="bg-white p-4 rounded border border-gray-200 shadow-sm"><strong class="text-blue-950 block mb-2">Jornada, domingos e feriados</strong><ul class="list-disc list-inside space-y-1 text-gray-600"><li><strong>Lei nº 10.101/2000</strong> — trabalho no comércio aos domingos e feriados.</li><li><strong>Portaria MTE nº 1.316/2026</strong> — regras aplicáveis ao trabalho em feriados no comércio.</li><li><strong>CLT, arts. 67 e 386</strong> — repouso semanal e escala dominical.</li><li><strong>Lei nº 605/1949</strong> — repouso semanal remunerado e feriados.</li></ul></div>
      <div class="bg-white p-4 rounded border border-gray-200 shadow-sm"><strong class="text-blue-950 block mb-2">SST e saúde preventiva</strong><ul class="list-disc list-inside space-y-1 text-gray-600"><li><strong>NR-1</strong> — GRO/PGR e fatores de risco psicossociais relacionados ao trabalho.</li><li><strong>NR-5</strong> — CIPA e documentação relacionada.</li><li><strong>NR-7</strong> — PCMSO, exames ocupacionais e prontuários.</li><li><strong>NR-17</strong> — ergonomia e organização do trabalho.</li><li><strong>Lei nº 15.377/2026</strong> — informação sobre vacinação, HPV, cânceres e exames preventivos.</li></ul></div>
      <div class="bg-white p-4 rounded border border-gray-200 shadow-sm"><strong class="text-blue-950 block mb-2">Faltas justificáveis</strong><ul class="list-disc list-inside space-y-1 text-gray-600"><li><strong>CLT, art. 473, texto compilado</strong> — referência principal para as hipóteses vigentes.</li><li><strong>Lei nº 14.457/2022</strong> — alterações dos incisos III e X.</li><li><strong>Lei nº 13.257/2016</strong> — acompanhamento de filho em consulta médica.</li><li><strong>Lei nº 13.767/2018</strong> — exames preventivos de câncer.</li><li><strong>Lei nº 15.377/2026</strong> — atualização relacionada à prevenção em saúde.</li></ul></div>
      <div class="bg-white p-4 rounded border border-gray-200 shadow-sm"><strong class="text-blue-950 block mb-2">Multas administrativas trabalhistas</strong><ul class="list-disc list-inside space-y-1 text-gray-600"><li><strong>Portaria MTE nº 1.131/2025</strong> — valores e critérios das multas administrativas.</li><li><strong>Portaria MTP nº 667/2021</strong> — processo administrativo trabalhista e parâmetros de aplicação.</li></ul></div>
      <div class="bg-white p-4 rounded border border-gray-200 shadow-sm"><strong class="text-blue-950 block mb-2">Guarda de documentos</strong><ul class="list-disc list-inside space-y-1 text-gray-600"><li><strong>Constituição Federal, art. 7º, XXIX</strong> — prescrição trabalhista.</li><li><strong>Portaria MTP nº 671/2021, arts. 152 e 157</strong> — RAIS e CAGED legados.</li><li><strong>NR-1, item 1.5.7.3.3.1</strong> — histórico das atualizações do PGR por, no mínimo, 20 anos.</li><li><strong>NR-5</strong> — documentação da CIPA por, no mínimo, 5 anos.</li><li><strong>NR-7, item 7.6.1.1</strong> — prontuário do empregado por, no mínimo, 20 anos após o desligamento.</li><li><strong>Decreto nº 10.854/2021, art. 14, com redação do Decreto nº 11.905/2024</strong> — eLIT em substituição ao livro impresso.</li><li><strong>IN PRES/INSS nº 128/2022</strong> e regras do PPP eletrônico — histórico previdenciário e documentação correlata.</li></ul></div>`;
    const nav=secao.querySelector(':scope > .cma-page-navigation');if(nav)secao.insertBefore(bloco,nav);else secao.appendChild(bloco);
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',incluir);else incluir();
})();
